
package soap.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DrugSoapAPIService", targetNamespace = "http://drugservice.hu", wsdlLocation = "file:/home/zokni/workstation/h2-database/conf/drugs.wsdl")
public class DrugSoapAPIService
    extends Service
{

    private final static URL DRUGSOAPAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException DRUGSOAPAPISERVICE_EXCEPTION;
    private final static QName DRUGSOAPAPISERVICE_QNAME = new QName("http://drugservice.hu", "DrugSoapAPIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/zokni/workstation/h2-database/conf/drugs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRUGSOAPAPISERVICE_WSDL_LOCATION = url;
        DRUGSOAPAPISERVICE_EXCEPTION = e;
    }

    public DrugSoapAPIService() {
        super(__getWsdlLocation(), DRUGSOAPAPISERVICE_QNAME);
    }

    public DrugSoapAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRUGSOAPAPISERVICE_QNAME, features);
    }

    public DrugSoapAPIService(URL wsdlLocation) {
        super(wsdlLocation, DRUGSOAPAPISERVICE_QNAME);
    }

    public DrugSoapAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRUGSOAPAPISERVICE_QNAME, features);
    }

    public DrugSoapAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DrugSoapAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DrugSoapAPI
     */
    @WebEndpoint(name = "DrugSoapAPIServicePort")
    public DrugSoapAPI getDrugSoapAPIServicePort() {
        return super.getPort(new QName("http://drugservice.hu", "DrugSoapAPIServicePort"), DrugSoapAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrugSoapAPI
     */
    @WebEndpoint(name = "DrugSoapAPIServicePort")
    public DrugSoapAPI getDrugSoapAPIServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://drugservice.hu", "DrugSoapAPIServicePort"), DrugSoapAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRUGSOAPAPISERVICE_EXCEPTION!= null) {
            throw DRUGSOAPAPISERVICE_EXCEPTION;
        }
        return DRUGSOAPAPISERVICE_WSDL_LOCATION;
    }

}
