create table `DISTRIBUTOR` (
  `NAME` TEXT NOT NULL,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

create table `INGREDIENT` (
  `NAME` TEXT NOT NULL,
  `AMOUNT` INTEGER NOT NULL,
  `DRUG_ID` BIGINT NOT NULL,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

create table `DRUG` (
  `NAME` TEXT NOT NULL,
  `DISTRIBUTOR_ID` BIGINT NOT NULL,
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

INSERT INTO DISTRIBUTOR VALUES ('JutaVit', 1);
INSERT INTO DISTRIBUTOR VALUES ('Dr. Aliment', 2);

INSERT INTO DRUG VALUES ('Lecitin PRO', 1, 1);
INSERT INTO DRUG VALUES ('Lizin-C', 2, 2);
INSERT INTO DRUG VALUES ('Magnézium + B6', 1, 3);

INSERT INTO INGREDIENT VALUES ('Lecitin', 1200, 1, 1);
INSERT INTO INGREDIENT VALUES ('L-izin', 714, 2, 2);
INSERT INTO INGREDIENT VALUES ('C vitamin', 30, 2, 3);
INSERT INTO INGREDIENT VALUES ('Magnézium', 250, 3, 4);
INSERT INTO INGREDIENT VALUES ('B6 vitamin', 2, 3, 5);
INSERT INTO INGREDIENT VALUES ('D3 vitamin', 10, 3, 6);